import { authClient } from '../auth/firebase-client.js';
const status = document.getElementById('adminStatus');
const garages = document.getElementById('adminGarages');
const reviews = document.getElementById('adminReviews');
function escapeHtml(value) { const node=document.createElement('span');node.textContent=String(value || '');return node.innerHTML; }
async function api(path, options) { return authClient.api(`/api/admin/${path}`, options); }
async function refresh() { try { const [garageData, reviewData] = await Promise.all([api('garages?status=pending'), api('garage-reviews?status=pending')]); garages.innerHTML = garageData.garages.length ? garageData.garages.map((garage) => `<article class="admin-item"><strong>${escapeHtml(garage.name)}</strong><p>${escapeHtml(garage.city)} · ${escapeHtml(garage.email)}</p><button data-garage="${garage.id}" data-status="active">Publier</button><button data-garage="${garage.id}" data-status="rejected">Rejeter</button></article>`).join('') : '<p>Aucune candidature en attente.</p>'; reviews.innerHTML = reviewData.reviews.length ? reviewData.reviews.map((review) => `<article class="admin-item"><strong>${review.rating}/5 · ${escapeHtml(review.authorName)}</strong><p>${escapeHtml(review.comment)}</p><button data-review="${review.id}" data-status="published">Publier</button><button data-review="${review.id}" data-status="rejected">Rejeter</button></article>`).join('') : '<p>Aucun avis en attente.</p>'; status.textContent = 'Administration prête.'; } catch (error) { status.textContent = error.message || 'Accès administrateur refusé.'; } }
document.addEventListener('click', async (event) => { const button = event.target.closest('[data-garage],[data-review]'); if (!button) return; button.disabled = true; try { if (button.dataset.garage) await api(`garages/${encodeURIComponent(button.dataset.garage)}/status`, { method:'PATCH', body:JSON.stringify({ status:button.dataset.status }) }); else await api(`garage-reviews/${encodeURIComponent(button.dataset.review)}/status`, { method:'PATCH', body:JSON.stringify({ status:button.dataset.status }) }); await refresh(); } catch (error) { status.textContent = error.message || 'Action impossible.'; button.disabled = false; } });
document.getElementById('adminGarageForm')?.addEventListener('submit', async (event) => { event.preventDefault(); const form=event.currentTarget; try { await api('garages',{ method:'POST', body:JSON.stringify(Object.fromEntries(new FormData(form))) }); form.reset(); await refresh(); } catch (error) { status.textContent=error.message || 'Création impossible.'; } });
await authClient.initialize();
if (!authClient.user) status.textContent = 'Connectez-vous avec un compte administrateur pour continuer.';
else refresh();
