export const INLINE_PROCEDURES = {
  "niveau et couleur de l'huile moteur": '<strong>Contrôle :</strong> véhicule à plat et moteur arrêté depuis au moins 5 minutes, essuyez la jauge, réinsérez-la puis vérifiez que le niveau reste entre MIN et MAX. Une huile laiteuse, mousseuse ou contenant des particules impose un diagnostic avant utilisation.',
  'liquide de refroidissement (ldr)': '<strong>Sécurité :</strong> contrôlez uniquement moteur froid. Le niveau doit se situer entre MIN et MAX ; recherchez une pellicule huileuse, des dépôts, une couleur anormale ou des traces séchées autour du vase et des durites.',
  'fuites visibles sous le véhicule': '<strong>Contrôle :</strong> stationnez sur un sol propre, observez après plusieurs heures puis inspectez sans vous placer sous un véhicule non sécurisé. Identifiez la couleur, la texture et l’emplacement de toute trace avant de démarrer.',
  'bruits anormaux au démarrage / ralenti': '<strong>Contrôle :</strong> moteur froid puis chaud, écoutez capot ouvert sans approcher vêtements ou mains des pièces mobiles. Notez la zone, la fréquence et l’évolution du bruit avec le régime moteur.',
  "fumée à l'échappement": '<strong>Contrôle :</strong> observez la couleur uniquement à l’extérieur, moteur froid puis chaud. Une fumée bleue, noire dense ou blanche persistante accompagnée d’une baisse de niveau impose un diagnostic avant de poursuivre la route.',
  'stabilité du ralenti': '<strong>Contrôle :</strong> moteur à température et consommateurs coupés, observez le compte-tours pendant une minute. Relevez les oscillations, ratés, vibrations ou calages et vérifiez si un témoin moteur apparaît.',
  'joint de culasse (indices)': '<strong>Sécurité :</strong> n’ouvrez jamais le circuit de refroidissement à chaud. Moteur froid, recherchez une émulsion sous le bouchon d’huile, des bulles continues dans le vase, une surpression rapide ou des pertes simultanées d’huile et de liquide.',
  'supports moteur': '<strong>Contrôle :</strong> frein de stationnement serré, observez les vibrations au ralenti et les mouvements excessifs lors de la mise en charge, sans vous placer devant le véhicule. Inspectez les silentblocs à la recherche de fissures ou d’affaissement.',
  'rouille au niveau du plancher': '<strong>Contrôle :</strong> soulevez les tapis et inspectez planchers, bas de caisse et passages de roues avec une lampe. Une perforation, un métal feuilleté ou de la corrosion près d’un ancrage nécessite un contrôle professionnel.',
  "longerons & points d'ancrage": '<strong>Contrôle :</strong> recherchez plis, soudures non régulières, peinture récente, déformation et corrosion autour des longerons et ancrages. Ne passez sous le véhicule que s’il est placé sur un pont ou des chandelles homologuées.',
  'fuites pont / différentiel': '<strong>Contrôle :</strong> inspectez le carter, les joints de sortie et les zones proches des cardans. Un simple suintement doit être surveillé ; des gouttes, un niveau bas ou un grondement exigent une intervention.',
  'jeu dans les rotules / triangles': '<strong>Sécurité :</strong> faites réaliser ce contrôle sur un pont ou avec des chandelles homologuées. Recherchez soufflets déchirés, déplacement anormal et claquement ; tout jeu de direction ou suspension doit être traité avant circulation.',
  'état des amortisseurs': '<strong>Contrôle :</strong> recherchez fuite d’huile, tige endommagée, ressort cassé et différence de hauteur. Un rebond répété, une tenue de route flottante ou une fuite franche justifie un contrôle sur banc.',
  'usure des pneus (les 4)': '<strong>Contrôle :</strong> mesurez la profondeur sur plusieurs points de chaque pneu et inspectez flancs, hernies, coupures et usure intérieure. Une usure irrégulière peut révéler un défaut de pression, géométrie ou suspension.',
  'état des jantes': '<strong>Contrôle :</strong> inspectez les faces intérieure et extérieure pour détecter fissures, déformations et impacts. Une vibration, une perte de pression ou une fissure impose l’immobilisation jusqu’au contrôle.',
  'alignement des panneaux': '<strong>Contrôle :</strong> comparez les jeux entre capot, ailes, portes et coffre des deux côtés. Des écarts irréguliers, vis marquées ou différences de peinture peuvent indiquer une réparation antérieure.',
  'présence de mastic / bondo': '<strong>Contrôle :</strong> sous une lumière rasante, recherchez ondulations et différences de texture ; utilisez une jauge d’épaisseur de peinture sur plusieurs points comparables. Évitez l’aimant sur les carrosseries en aluminium ou composites.',
  'qualité et homogénéité de la peinture': '<strong>Contrôle :</strong> examinez le véhicule à la lumière naturelle sous plusieurs angles. Recherchez différences de teinte, brouillard de peinture sur joints, coulures, raccords et variations d’épaisseur.',
  'feux avant (croisement / route / clignotants)': '<strong>Contrôle :</strong> testez chaque fonction contact mis et vérifiez optiques, fixation, condensation et réglage apparent. Une optique cassée, un clignotant défaillant ou un faisceau incorrect doit être corrigé.',
  'feux arrière & stop': '<strong>Contrôle :</strong> demandez à une seconde personne d’actionner la pédale ou utilisez un reflet pour vérifier les feux stop. Testez aussi positions et clignotants, puis recherchez fissures et humidité.',
  'feux de recul & antibrouillard': '<strong>Contrôle :</strong> frein serré et véhicule immobilisé, mettez le contact et engagez la marche arrière sans démarrer si possible. Vérifiez ensuite chaque antibrouillard conformément à l’équipement du véhicule.',
  'état des sièges': '<strong>Contrôle :</strong> testez glissières, verrouillage, réglages, appuie-têtes et ceintures. Aucun siège ne doit bouger sur ses ancrages et aucun témoin d’airbag ne doit rester allumé.',
  'ciel de toit': '<strong>Contrôle :</strong> recherchez décollement, affaissement, humidité et traces autour des montants ou du toit ouvrant. Une humidité persistante nécessite la recherche de l’entrée d’eau.',
  'climatisation / chauffage': '<strong>Contrôle :</strong> testez toutes les vitesses de ventilation, les orientations et les températures. Notez les bruits, odeurs, variations de débit et l’enclenchement du compresseur lorsque le véhicule en possède un.',
  'vitres électriques (les 4)': '<strong>Contrôle :</strong> actionnez chaque vitre depuis sa commande locale et la commande conducteur. Vérifiez montée régulière, fonction antipincement et absence de bruit ou ralentissement anormal.',
  "odeurs / traces d'humidité": '<strong>Contrôle :</strong> inspectez tapis, dessous de moquette, coffre et logement de roue de secours. Odeur de moisi, buée récurrente ou isolant humide signale une infiltration à localiser.',
  "fluidité de l'accélération": '<strong>Contrôle :</strong> sur une route sûre, accélérez progressivement à plusieurs régimes sans dépasser les limitations. Notez trous, à-coups, fumée, vibrations ou témoins ; interrompez l’essai en cas de perte de puissance dangereuse.',
  'passage des vitesses': '<strong>Contrôle :</strong> moteur froid puis chaud, vérifiez chaque rapport à faible charge. Craquement, patinage, retard d’engagement ou choc marqué nécessite un diagnostic de boîte ou d’embrayage.',
  'test de braquage': '<strong>Contrôle :</strong> à très basse vitesse dans une zone dégagée, braquez progressivement des deux côtés sans maintenir longtemps la direction en butée. Recherchez claquement, point dur et différence d’assistance.',
  'freinage': '<strong>Sécurité :</strong> avant l’essai, vérifiez une pédale ferme et l’absence de témoin rouge. À faible vitesse dans une zone sûre, contrôlez efficacité, bruits et déviation ; immobilisez le véhicule si la pédale s’enfonce ou si le freinage est asymétrique.',
  'comportement à vitesse stabilisée': '<strong>Contrôle :</strong> sur une route régulière et sûre, maintenez une vitesse légale constante. Notez vibrations selon la vitesse, dérive, grondement et mouvements du volant sans relâcher son contrôle.',
  'code p1000 détecté ?': '<strong>P1000 :</strong> les moniteurs OBD ne sont pas tous terminés, souvent après effacement des défauts ou débranchement de batterie. Vérifiez l’historique et effectuez le cycle de conduite constructeur avant de conclure à l’absence de défaut.',
};

export const SYMPTOMS_DATABASE = {
  'perte de puissance': {
    type: 'report',
    fault_code: 'N/A',
    root_cause: 'Mode dégradé ou défaut d’alimentation en air, carburant ou suralimentation à confirmer par lecture des codes et mesures réelles.',
    action_plan: '1. Relever tous les codes défaut sans les effacer. 2. Contrôler les niveaux et rechercher une durite débranchée ou une fuite visible. 3. Comparer les valeurs de pression, débit d’air et carburant aux spécifications constructeur. 4. Immobiliser le véhicule si un témoin rouge, une fumée importante ou une surchauffe accompagne la perte de puissance.',
  },
  'moteur ne démarre pas': {
    type: 'report',
    fault_code: 'N/A',
    root_cause: 'Défaut possible de batterie, alimentation électrique, autorisation antidémarrage, démarreur, carburant ou synchronisation moteur.',
    action_plan: '1. Mesurer la tension batterie au repos et pendant la tentative. 2. Observer si le démarreur entraîne le moteur et relever les témoins. 3. Lire les codes de tous les calculateurs. 4. Contrôler alimentation carburant et synchronisation uniquement selon la procédure constructeur.',
  },
  'surchauffe moteur': {
    type: 'report',
    fault_code: 'N/A',
    root_cause: 'Défaillance possible du niveau de liquide, d’une fuite, de la circulation, du ventilateur ou de la régulation thermique.',
    action_plan: '1. Arrêter et immobiliser le véhicule immédiatement. 2. Ne jamais ouvrir le vase à chaud. 3. Après refroidissement complet, contrôler le niveau et les fuites visibles. 4. Faire contrôler la mise en pression, le thermostat, la pompe et la commande des ventilateurs.',
  },
  'fumée blanche persistante': {
    type: 'report',
    fault_code: 'N/A',
    root_cause: 'Présence possible de liquide de refroidissement dans la combustion ou combustion incomplète, à distinguer de la condensation normale à froid.',
    action_plan: '1. Immobiliser si la fumée persiste moteur chaud ou si le niveau baisse. 2. Contrôler les niveaux uniquement moteur froid. 3. Effectuer un test de pression du circuit et une recherche de gaz de combustion. 4. Contrôler l’injection si le circuit de refroidissement est étanche.',
  },
  'batterie se décharge': {
    type: 'report',
    fault_code: 'N/A',
    root_cause: 'Batterie dégradée, défaut de charge ou consommation électrique à l’arrêt à confirmer par mesures.',
    action_plan: '1. Mesurer la tension et tester la capacité de la batterie. 2. Vérifier la tension de charge selon le système du véhicule. 3. Mesurer le courant de repos après endormissement des calculateurs. 4. Isoler le circuit consommateur sans débrancher arbitrairement les équipements de sécurité.',
  },
  'bruit au freinage': {
    type: 'report',
    fault_code: 'N/A',
    root_cause: 'Usure, contamination, corrosion ou défaut mécanique du système de freinage à contrôler immédiatement.',
    action_plan: '1. Immobiliser en cas de baisse d’efficacité, pédale anormale ou témoin rouge. 2. Contrôler l’épaisseur des garnitures et l’état des disques. 3. Rechercher fuite, grippage et jeu. 4. Réaliser un essai de freinage sécurisé après réparation.',
  },
};

export const OBD_SCENARIOS = {
  P0300: {
    type: 'report',
    fault_code: 'P0300',
    root_cause: 'Ratés de combustion aléatoires ou multiples détectés ; l’allumage, l’injection, l’admission et la mécanique doivent être contrôlés avant remplacement de pièces.',
    action_plan: '1. Relever les données figées et compteurs de ratés. 2. Contrôler bougies, bobines et connecteurs selon la motorisation. 3. Vérifier prises d’air, pression carburant et injecteurs. 4. Effectuer les contrôles de compression et synchronisation si nécessaire.',
  },
  P0301: {
    type: 'report',
    fault_code: 'P0301',
    root_cause: 'Ratés de combustion détectés sur le cylindre 1 ; la cause peut relever de l’allumage, de l’injection, d’une prise d’air ou de la mécanique.',
    action_plan: '1. Relever les données figées et le compteur de ratés. 2. Contrôler bougie, bobine, injecteur et faisceau du cylindre 1. 3. Rechercher une prise d’air localisée. 4. Contrôler compression et étanchéité avant tout remplacement.',
  },
  P0302: {
    type: 'report',
    fault_code: 'P0302',
    root_cause: 'Ratés de combustion détectés sur le cylindre 2 ; la cause peut relever de l’allumage, de l’injection, d’une prise d’air ou de la mécanique.',
    action_plan: '1. Relever les données figées et le compteur de ratés. 2. Contrôler bougie, bobine, injecteur et faisceau du cylindre 2. 3. Rechercher une prise d’air localisée. 4. Contrôler compression et étanchéité avant tout remplacement.',
  },
  P0303: {
    type: 'report',
    fault_code: 'P0303',
    root_cause: 'Ratés de combustion détectés sur le cylindre 3 ; la cause peut relever de l’allumage, de l’injection, d’une prise d’air ou de la mécanique.',
    action_plan: '1. Relever les données figées et le compteur de ratés. 2. Contrôler bougie, bobine, injecteur et faisceau du cylindre 3. 3. Rechercher une prise d’air localisée. 4. Contrôler compression et étanchéité avant tout remplacement.',
  },
  P0304: {
    type: 'report',
    fault_code: 'P0304',
    root_cause: 'Ratés de combustion détectés sur le cylindre 4 ; la cause peut relever de l’allumage, de l’injection, d’une prise d’air ou de la mécanique.',
    action_plan: '1. Relever les données figées et le compteur de ratés. 2. Contrôler bougie, bobine, injecteur et faisceau du cylindre 4. 3. Rechercher une prise d’air localisée. 4. Contrôler compression et étanchéité avant tout remplacement.',
  },
  P0171: {
    type: 'report',
    fault_code: 'P0171',
    root_cause: 'Mélange trop pauvre détecté sur la banque 1, souvent lié à une entrée d’air non mesurée, une mesure d’air erronée ou une alimentation carburant insuffisante.',
    action_plan: '1. Relever adaptations carburant et données figées. 2. Rechercher une prise d’air et une fuite d’échappement en amont de la sonde. 3. Contrôler débitmètre, pression carburant et injecteurs. 4. Vérifier la sonde uniquement après validation des circuits.',
  },
  P0299: {
    type: 'report',
    fault_code: 'P0299',
    root_cause: 'Pression de suralimentation insuffisante ; une fuite, la commande du turbo, un capteur ou le turbocompresseur peuvent être en cause.',
    action_plan: '1. Contrôler les durites et l’échangeur sous pression. 2. Comparer pression demandée et mesurée. 3. Tester électrovanne, actionneur et dépression selon le montage. 4. Contrôler le turbo et la lubrification avant remplacement.',
  },
  P0401: {
    type: 'report',
    fault_code: 'P0401',
    root_cause: 'Débit EGR insuffisant, pouvant résulter d’un conduit obstrué, d’une vanne ou commande défaillante, ou d’une mesure incorrecte.',
    action_plan: '1. Relever les données figées. 2. Commander l’EGR avec l’outil de diagnostic et observer les mesures. 3. Contrôler alimentation, commande et conduits. 4. Nettoyer ou remplacer uniquement après confirmation du défaut.',
  },
  P0420: {
    type: 'report',
    fault_code: 'P0420',
    root_cause: 'Efficacité du catalyseur sous le seuil sur la banque 1 ; des ratés, une fuite d’échappement ou une sonde peuvent fausser le diagnostic.',
    action_plan: '1. Corriger d’abord tout raté ou défaut de richesse. 2. Rechercher les fuites d’échappement. 3. Comparer les signaux des sondes amont et aval. 4. Confirmer l’efficacité du catalyseur avant remplacement.',
  },
  P1000: {
    type: 'report',
    fault_code: 'P1000',
    root_cause: 'Cycle de contrôle OBD non terminé, généralement après effacement de la mémoire ou perte d’alimentation ; ce code ne désigne pas à lui seul une panne de composant.',
    action_plan: '1. Vérifier si les codes ont récemment été effacés. 2. Contrôler l’état des moniteurs OBD. 3. Effectuer le cycle de conduite prévu par le constructeur. 4. Relire les défauts et moniteurs sans effacer la mémoire.',
  },
};

const INLINE_ALIASES = {
  "niveau d'huile": "niveau et couleur de l'huile moteur",
  'huile moteur': "niveau et couleur de l'huile moteur",
  'jauge huile': "niveau et couleur de l'huile moteur",
  'ldr': 'liquide de refroidissement (ldr)',
  'liquide de refroidissement': 'liquide de refroidissement (ldr)',
  'vase expansion': 'liquide de refroidissement (ldr)',
  'fuite moteur': 'fuites visibles sous le véhicule',
  'fuite sous voiture': 'fuites visibles sous le véhicule',
  'bruit moteur': 'bruits anormaux au démarrage / ralenti',
  'claquement moteur': 'bruits anormaux au démarrage / ralenti',
  'fumée échappement': "fumée à l'échappement",
  'fumée bleue': "fumée à l'échappement",
  'fumée noire': "fumée à l'échappement",
  'fumée blanche': "fumée à l'échappement",
  'ralenti instable': 'stabilité du ralenti',
  'silentbloc moteur': 'supports moteur',
  'rouille': 'rouille au niveau du plancher',
  'corrosion châssis': 'rouille au niveau du plancher',
  'longerons': "longerons & points d'ancrage",
  'rotules': 'jeu dans les rotules / triangles',
  'triangles': 'jeu dans les rotules / triangles',
  'amortisseurs': 'état des amortisseurs',
  'pneus': 'usure des pneus (les 4)',
  'usure pneus': 'usure des pneus (les 4)',
  'jantes': 'état des jantes',
  'carrosserie repeinte': 'qualité et homogénéité de la peinture',
  'peinture': 'qualité et homogénéité de la peinture',
  'phares': 'feux avant (croisement / route / clignotants)',
  'feux stop': 'feux arrière & stop',
  'climatisation': 'climatisation / chauffage',
  'chauffage': 'climatisation / chauffage',
  'vitres électriques': 'vitres électriques (les 4)',
  'infiltration eau': "odeurs / traces d'humidité",
  'accélération': "fluidité de l'accélération",
  'boîte de vitesses': 'passage des vitesses',
  'embrayage': 'passage des vitesses',
  'direction': 'test de braquage',
  'freins': 'freinage',
  'vibrations volant': 'comportement à vitesse stabilisée',
  'p1000': 'code p1000 détecté ?',
};

for (const [alias, canonicalKey] of Object.entries(INLINE_ALIASES)) {
  INLINE_PROCEDURES[alias] = INLINE_PROCEDURES[canonicalKey];
}

Object.assign(INLINE_PROCEDURES, {
  batterie: '<strong>Contrôle :</strong> mesurez la tension au repos après stabilisation, puis pendant le démarrage, et réalisez un test de capacité adapté à la technologie de batterie. Une tension correcte à vide ne suffit pas à confirmer son état.',
  alternateur: '<strong>Contrôle :</strong> mesurez la tension et le courant de charge selon la stratégie du véhicule, avec consommateurs activés. Sur un système piloté, une valeur variable est normale : comparez la consigne et la mesure avec l’outil de diagnostic.',
  démarreur: '<strong>Contrôle :</strong> mesurez la chute de tension des câbles positif et masse pendant l’actionnement, puis le courant absorbé. Sécurisez le véhicule au point mort ou en position P avant toute mesure.',
  'courroie de distribution': '<strong>Contrôle :</strong> vérifiez l’échéance constructeur, les justificatifs, les fuites proches et l’état visible sans déposer de carter moteur tournant. Un doute sur l’historique impose le remplacement préventif selon la procédure constructeur.',
  'chaîne de distribution': '<strong>Contrôle :</strong> recherchez bruit au démarrage, défauts de corrélation et valeurs d’adaptation anormales. La confirmation exige les outils et valeurs constructeur ; un bruit seul ne condamne pas la chaîne.',
  'courroie accessoires': '<strong>Contrôle :</strong> moteur arrêté, recherchez craquelures, effilochage, contamination et défaut d’alignement. Contrôlez aussi galets, tendeur et poulie roue libre avant de remplacer la courroie.',
  turbo: '<strong>Contrôle :</strong> inspectez admission, échangeur et durites, puis comparez pression demandée et mesurée. Un film d’huile léger ne condamne pas le turbo ; contrôlez jeu, commande et lubrification selon les limites constructeur.',
  injecteurs: '<strong>Contrôle :</strong> relevez corrections, pression carburant et qualité de combustion, puis réalisez un test de retour ou d’équilibrage adapté au système. Ne desserrez jamais une canalisation haute pression moteur tournant.',
  'vanne egr': '<strong>Contrôle :</strong> commandez la vanne avec l’outil de diagnostic et comparez position demandée, position réelle et variation du débit d’air. Vérifiez conduits et alimentation avant nettoyage ou remplacement.',
  fap: '<strong>Contrôle :</strong> relevez charge calculée, pression différentielle, températures et historique de régénération. Corrigez les défauts moteur et capteurs avant toute régénération forcée, qui doit respecter les conditions de sécurité constructeur.',
  'filtre à particules': '<strong>Contrôle :</strong> relevez charge calculée, pression différentielle, températures et historique de régénération. Corrigez les défauts moteur et capteurs avant toute régénération forcée, qui doit respecter les conditions de sécurité constructeur.',
  adblue: '<strong>Contrôle :</strong> relevez qualité, niveau, pression, températures et défauts SCR. Portez des protections, évitez toute contamination et suivez la procédure d’amorçage constructeur après intervention.',
  catalyseur: '<strong>Contrôle :</strong> corrigez d’abord ratés, défauts de richesse et fuites d’échappement. Comparez ensuite températures et signaux amont/aval ; un code d’efficacité ne suffit pas à condamner le catalyseur.',
  'sonde lambda': '<strong>Contrôle :</strong> analysez chauffage, alimentation, masse et réponse du signal avec les adaptations carburant. Une valeur anormale peut être la conséquence d’une prise d’air, d’un raté ou d’une fuite d’échappement.',
  débitmètre: '<strong>Contrôle :</strong> vérifiez alimentation, masse, signal et cohérence avec régime, charge et pression d’admission. Inspectez prises d’air et filtre avant de conclure à un débitmètre défaillant.',
  'capteur pmh': '<strong>Contrôle :</strong> observez le régime moteur pendant le lancement et contrôlez signal, alimentation et faisceau à l’oscilloscope si nécessaire. Vérifiez aussi la corrélation avec l’arbre à cames.',
  abs: '<strong>Sécurité :</strong> lisez les défauts du calculateur ABS et comparez les quatre vitesses de roue. Contrôlez capteur, cible, roulement et faisceau ; immobilisez le véhicule si le freinage est dégradé ou si un témoin rouge est allumé.',
  airbag: '<strong>Sécurité :</strong> ne mesurez jamais directement un déclencheur avec un multimètre. Lisez les codes SRS, coupez l’alimentation selon le délai constructeur et contrôlez connecteurs et faisceaux uniquement avec la procédure dédiée.',
  'direction assistée': '<strong>Sécurité :</strong> contrôlez témoins, alimentation, défauts et effort de direction. Une assistance intermittente, un point dur ou un témoin rouge impose l’immobilisation et un diagnostic du système.',
  'liquide de frein': '<strong>Contrôle :</strong> vérifiez niveau, couleur, fuites et teneur en eau avec un appareil adapté. Une baisse de niveau ou une pédale molle nécessite l’immobilisation et la recherche immédiate d’une fuite ou d’une usure.',
  'vin numéro de série': '<strong>Contrôle :</strong> comparez le VIN frappé, la plaque constructeur, le pare-brise et les documents. Toute différence, altération ou fixation suspecte doit être clarifiée avant l’achat.',
  'historique entretien': '<strong>Contrôle :</strong> rapprochez factures, kilométrages, contrôles techniques et échéances constructeur. Vérifiez les opérations majeures avec les références et dates, pas uniquement avec un tampon de carnet.',
  'rappels constructeur': '<strong>Contrôle :</strong> utilisez le VIN sur le portail officiel du constructeur ou auprès du réseau pour vérifier les campagnes ouvertes. Un rappel de sécurité doit être traité selon les instructions du constructeur.',
});

function symptomScenario(rootCause, actionPlan, keywords = []) {
  return {
    type: 'report',
    fault_code: 'N/A',
    root_cause: rootCause,
    action_plan: actionPlan,
    keywords,
  };
}

Object.assign(SYMPTOMS_DATABASE, {
  'voyant moteur allumé': symptomScenario(
    'Un défaut moteur ou antipollution est mémorisé ; le voyant seul ne permet pas d’identifier la cause.',
    '1. Relever les codes, statuts et données figées sans les effacer. 2. Vérifier si le voyant est fixe ou clignotant. 3. Contrôler les circuits indiqués par les codes avec les valeurs constructeur. 4. Immobiliser en cas de voyant clignotant accompagné de ratés importants.',
    ['check engine', 'témoin moteur', 'mil allumé'],
  ),
  'voyant batterie allumé': symptomScenario(
    'Défaut possible du système de charge, de la courroie accessoires, du câblage ou de la gestion électrique.',
    '1. Couper les consommateurs non essentiels. 2. Vérifier courroie et connexions moteur arrêté. 3. Mesurer tension et courant de charge. 4. Immobiliser si la température monte, si la direction durcit ou si la tension chute.',
    ['témoin batterie', 'défaut charge'],
  ),
  'voyant huile allumé': symptomScenario(
    'Pression d’huile potentiellement insuffisante ou défaut du circuit de mesure.',
    '1. Arrêter immédiatement le moteur. 2. Contrôler le niveau après stabilisation. 3. Ne pas redémarrer si le niveau est correct mais le voyant persiste. 4. Mesurer la pression avec un manomètre et contrôler crépine, pompe et circuit.',
    ['pression huile', 'témoin huile rouge'],
  ),
  'voyant température allumé': symptomScenario(
    'Surchauffe réelle ou défaut de mesure/commande du refroidissement.',
    '1. Arrêter et immobiliser le véhicule. 2. Ne pas ouvrir le vase à chaud. 3. Après refroidissement, vérifier niveau et fuites. 4. Contrôler sonde, ventilateurs, thermostat, circulation et pression du circuit.',
    ['température moteur haute', 'voyant liquide refroidissement'],
  ),
  'voyant abs allumé': symptomScenario(
    'L’antiblocage est indisponible ou dégradé, souvent à cause d’un capteur, d’une cible, d’une alimentation ou du réseau.',
    '1. Lire les codes ABS. 2. Comparer les vitesses de roue en roulant très lentement. 3. Contrôler faisceaux, cibles et roulements. 4. Immobiliser si un témoin rouge ou une anomalie de freinage accompagne le voyant.',
    ['témoin abs', 'défaut abs'],
  ),
  'voyant airbag allumé': symptomScenario(
    'Le système de retenue supplémentaire a détecté un défaut et peut être partiellement indisponible.',
    '1. Lire les codes SRS avec un outil compatible. 2. Ne pas sonder directement les déclencheurs. 3. Contrôler alimentation et connecteurs selon la procédure constructeur. 4. Réparer avant utilisation normale du véhicule.',
    ['témoin srs', 'défaut airbag'],
  ),
  'démarrage difficile à froid': symptomScenario(
    'Défaut possible de batterie, préchauffage, enrichissement, pression carburant, capteurs de température ou compression.',
    '1. Mesurer batterie et vitesse de lancement. 2. Relever températures moteur froid et pression carburant. 3. Contrôler préchauffage sur diesel. 4. Vérifier injection, prises d’air et compression selon les résultats.',
    ['démarre mal à froid', 'long à démarrer à froid'],
  ),
  'démarrage difficile à chaud': symptomScenario(
    'Défaut possible de pression carburant, capteur de régime, démarreur, alimentation électrique ou dérive thermique.',
    '1. Comparer vitesse de lancement à froid et à chaud. 2. Relever régime, synchronisation et pression pendant la panne. 3. Contrôler chutes de tension. 4. Tester les composants uniquement lorsque le défaut est présent.',
    ['démarre mal à chaud', 'ne redémarre pas à chaud'],
  ),
  'moteur cale': symptomScenario(
    'Perte possible d’alimentation électrique ou carburant, défaut de régime/synchronisation, admission ou gestion de ralenti.',
    '1. Relever les codes et données au moment du calage. 2. Contrôler tension, régime, pression carburant et position papillon. 3. Rechercher prise d’air et faux contact. 4. Ne pas circuler si le calage survient en roulant.',
    ['calage moteur', 'cale au ralenti', 'cale en roulant'],
  ),
  'moteur broute': symptomScenario(
    'Ratés de combustion ou irrégularité d’alimentation en air/carburant à confirmer par les compteurs de ratés et les mesures.',
    '1. Relever codes et cylindres concernés. 2. Contrôler allumage sur essence. 3. Vérifier pression, injecteurs et prises d’air. 4. Contrôler compression si le défaut reste localisé.',
    ['à-coups moteur', 'moteur tourne sur trois cylindres', 'ratés moteur'],
  ),
  'consommation carburant élevée': symptomScenario(
    'Richesse excessive, mesure d’air/température erronée, pression ou injecteur défaillant, résistance mécanique ou usage à caractériser.',
    '1. Confirmer la consommation par plein complet. 2. Relever adaptations, températures et sondes. 3. Contrôler pression carburant, injecteurs, admission et échappement. 4. Vérifier pneus, freins et conditions d’utilisation.',
    ['surconsommation', 'consomme trop'],
  ),
  'odeur de carburant': symptomScenario(
    'Fuite de carburant ou de vapeurs, défaut d’étanchéité EVAP ou combustion incomplète.',
    '1. Couper le moteur et éloigner toute source d’ignition. 2. Immobiliser si l’odeur est forte ou si une fuite est visible. 3. Contrôler réservoir, conduites, rampe, injecteurs et EVAP. 4. Mettre le circuit sous test selon la procédure constructeur.',
    ['odeur essence', 'odeur gasoil', 'fuite carburant'],
  ),
  'fumée bleue': symptomScenario(
    'Combustion probable d’huile moteur par segmentation, guides, turbo ou ventilation de carter.',
    '1. Contrôler niveau et consommation d’huile. 2. Observer quand la fumée apparaît. 3. Vérifier reniflard, turbo et admission. 4. Mesurer compression/étanchéité si nécessaire et immobiliser si le niveau chute rapidement.',
    ['échappement bleu', 'brûle huile'],
  ),
  'fumée noire': symptomScenario(
    'Mélange trop riche ou manque d’air, avec défaut possible d’admission, suralimentation, EGR, mesure d’air ou injection.',
    '1. Relever codes, débit d’air, pression et richesse. 2. Contrôler filtre, durites et échangeur. 3. Vérifier EGR et injecteurs. 4. Éviter les fortes charges jusqu’au diagnostic.',
    ['échappement noir'],
  ),
  'sifflement moteur': symptomScenario(
    'Fuite d’air, de suralimentation, de dépression, courroie ou roulement à localiser avant remplacement.',
    '1. Localiser le bruit sans approcher les pièces mobiles. 2. Inspecter durites et courroie moteur arrêté. 3. Tester l’admission sous pression si nécessaire. 4. Contrôler poulies et turbo selon la zone identifiée.',
    ['sifflement turbo', 'bruit aigu moteur'],
  ),
  'claquement moteur': symptomScenario(
    'Jeu mécanique, combustion anormale, pression d’huile ou accessoire pouvant provoquer un claquement.',
    '1. Contrôler immédiatement niveau et pression d’huile. 2. Localiser fréquence et zone. 3. Comparer froid/chaud et charge/ralenti. 4. Immobiliser si le bruit est fort, nouveau ou accompagné d’un voyant.',
    ['cognement moteur', 'cliquetis moteur'],
  ),
  'vibrations au ralenti': symptomScenario(
    'Ratés de combustion, support moteur, volant moteur ou charge accessoire à distinguer par mesures.',
    '1. Relever compteurs de ratés et régime. 2. Comparer avec climatisation engagée et rapports sélectionnés. 3. Inspecter supports et échappement. 4. Contrôler combustion et volant moteur selon les symptômes associés.',
    ['moteur tremble', 'vibre au ralenti'],
  ),
  'embrayage patine': symptomScenario(
    'Transmission de couple insuffisante par usure ou contamination de l’embrayage, ou défaut de commande.',
    '1. Comparer hausse du régime et accélération sous charge modérée. 2. Contrôler course et commande. 3. Rechercher une fuite de joint pouvant contaminer le disque. 4. Éviter les fortes charges jusqu’à réparation.',
    ['patinage embrayage', 'régime monte sans accélérer'],
  ),
  'boîte automatique donne des à-coups': symptomScenario(
    'Pression hydraulique, adaptation, huile, électrovanne, embrayage interne ou commande moteur/réseau à contrôler.',
    '1. Relever tous les codes moteur et boîte. 2. Vérifier niveau, état et température d’huile selon la procédure. 3. Comparer pressions, glissements et rapports commandés. 4. Ne pas réinitialiser les adaptations avant diagnostic.',
    ['à-coups boîte auto', 'boîte tape', 'passage vitesse brutal'],
  ),
  'direction dure': symptomScenario(
    'Défaut possible d’assistance électrique/hydraulique, d’alimentation, de pression, de géométrie ou d’élément mécanique.',
    '1. Immobiliser si l’effort varie brutalement ou si un témoin rouge apparaît. 2. Contrôler pneus, niveaux applicables et courroie. 3. Lire les défauts et mesurer alimentation/pression. 4. Vérifier absence de point dur mécanique.',
    ['volant dur', 'perte direction assistée'],
  ),
  'véhicule tire au freinage': symptomScenario(
    'Freinage asymétrique, pneu, suspension ou géométrie pouvant compromettre la stabilité.',
    '1. Immobiliser le véhicule. 2. Contrôler pression et état des pneus. 3. Inspecter disques, plaquettes, flexibles, étriers et fuites. 4. Mesurer les forces sur banc après réparation.',
    ['tire à droite freinage', 'tire à gauche freinage'],
  ),
  'pédale de frein molle': symptomScenario(
    'Présence d’air, fuite, liquide dégradé, maître-cylindre ou défaut hydraulique.',
    '1. Immobiliser immédiatement. 2. Contrôler niveau et fuites sans rouler. 3. Tester le circuit et le maître-cylindre. 4. Purger selon la procédure ABS constructeur puis vérifier sur banc.',
    ['pédale spongieuse', 'frein s’enfonce'],
  ),
  'vibration au freinage': symptomScenario(
    'Variation d’épaisseur ou faux-rond des disques, jeu de train roulant, moyeu ou roue à mesurer.',
    '1. Contrôler serrage et état des roues. 2. Mesurer faux-rond du moyeu et du disque. 3. Contrôler épaisseur, étriers et silentblocs. 4. Corriger la cause avant remplacement des disques.',
    ['volant tremble au freinage', 'freinage vibre'],
  ),
  'vibration à vitesse élevée': symptomScenario(
    'Déséquilibrage ou déformation de roue, pneu, transmission, roulement ou jeu de suspension.',
    '1. Contrôler pneus, jantes et serrage. 2. Équilibrer et mesurer le voile. 3. Vérifier jeux, roulements et transmissions. 4. Immobiliser en cas de hernie, desserrage ou vibration forte.',
    ['vibre à 110', 'vibre sur autoroute'],
  ),
  'bruit de roulement': symptomScenario(
    'Roulement de roue, pneu facetté, transmission ou différentiel à distinguer selon vitesse et charge.',
    '1. Comparer le bruit selon revêtement, vitesse et virage. 2. Inspecter pneus. 3. Contrôler jeux et rotation sur pont. 4. Localiser avec capteurs acoustiques si nécessaire.',
    ['grondement roue', 'ronronnement vitesse'],
  ),
  'climatisation ne refroidit plus': symptomScenario(
    'Charge de réfrigérant insuffisante, fuite, commande, capteur, compresseur ou échange thermique défaillant.',
    '1. Relever défauts et températures. 2. Vérifier pressions avec une station adaptée. 3. Rechercher la fuite avant recharge. 4. Contrôler ventilateurs, compresseur et volets selon les résultats.',
    ['clim ne fait plus de froid', 'air conditionné chaud'],
  ),
  'ventilateur moteur tourne en permanence': symptomScenario(
    'Mode de secours lié à un défaut de température, pression de climatisation, relais, commande ou communication.',
    '1. Relever codes et températures affichées moteur froid. 2. Contrôler capteurs et connecteurs. 3. Vérifier relais/module de commande. 4. Confirmer la température réelle avant de remplacer le ventilateur.',
    ['ventilateur ne s’arrête pas', 'moto ventilateur toujours allumé'],
  ),
  'régénération fap fréquente': symptomScenario(
    'Production excessive de suies, trajets incompatibles, mesure de pression/température erronée ou filtre chargé.',
    '1. Relever charge, distance entre régénérations et pression différentielle. 2. Contrôler thermostats, EGR, admission et injection. 3. Vérifier capteurs et tuyaux. 4. Ne lancer une régénération forcée qu’après validation des conditions de sécurité.',
    ['fap se régénère souvent', 'ventilateur après arrêt diesel'],
  ),
  'message défaut adblue': symptomScenario(
    'Défaut possible de qualité, niveau, chauffage, pompe, injecteur, capteur NOx ou efficacité SCR.',
    '1. Relever codes, kilométrage avant interdiction de démarrage et données SCR. 2. Vérifier qualité et cristallisation. 3. Tester pression, dosage et capteurs. 4. Effectuer amorçage et réinitialisation uniquement après réparation.',
    ['défaut antipollution adblue', 'urée défaut', 'démarrage impossible adblue'],
  ),
});

const OBD_ACTION_PLANS = {
  timing: '1. Relever données figées et valeurs de synchronisation. 2. Contrôler niveau, pression et qualité d’huile. 3. Vérifier alimentation, faisceau et actionneur. 4. Contrôler le calage mécanique avec les outils constructeur avant remplacement.',
  air: '1. Relever données figées et comparer valeurs demandées/mesurées. 2. Contrôler alimentation, masse et signal du capteur. 3. Rechercher fuite, obstruction ou contamination du circuit. 4. Confirmer avec une mesure indépendante avant remplacement.',
  fuel: '1. Relever pression demandée/mesurée et adaptations. 2. Contrôler alimentation électrique, étanchéité et qualité du carburant. 3. Tester pompe, régulateur et injecteurs selon la procédure. 4. Ne jamais ouvrir un circuit haute pression moteur tournant.',
  ignition: '1. Relever données figées et compteurs de ratés. 2. Contrôler bougies, bobines, injecteurs et faisceaux du cylindre concerné. 3. Rechercher prises d’air. 4. Contrôler compression et étanchéité avant remplacement.',
  emissions: '1. Relever données figées et corriger d’abord les défauts moteur associés. 2. Contrôler alimentation, conduits et fuites. 3. Commander le composant et comparer les capteurs. 4. Confirmer l’efficacité avant nettoyage ou remplacement.',
  electrical: '1. Contrôler batterie, fusibles, alimentations et masses sous charge. 2. Relever données figées et défauts de tous les calculateurs. 3. Tester continuité, isolement et chute de tension du faisceau. 4. Confirmer le calculateur seulement après validation des circuits.',
  transmission: '1. Relever les codes moteur et transmission avec données figées. 2. Vérifier niveau, état et température du fluide selon la procédure. 3. Comparer vitesses, rapports, pressions et glissements. 4. Contrôler faisceau et hydraulique avant toute dépose.',
  cooling: '1. Immobiliser en cas de surchauffe réelle. 2. Contrôler niveau et fuites uniquement moteur froid. 3. Comparer température mesurée et réelle. 4. Tester thermostat, circulation, ventilateurs et pression du circuit.',
  network: '1. Tester la batterie et les alimentations de tous les modules concernés. 2. Effectuer un scan réseau complet. 3. Contrôler résistances, tensions et intégrité du bus selon le constructeur. 4. Isoler le segment fautif avant de condamner un calculateur.',
};

function createObdScenario(code, condition, possibleCauses, family = 'electrical') {
  return {
    type: 'report',
    fault_code: code,
    root_cause: `${condition}. Causes possibles : ${possibleCauses}. Le code identifie une condition détectée, pas automatiquement une pièce défectueuse.`,
    action_plan: OBD_ACTION_PLANS[family],
  };
}

const EXTRA_OBD_DEFINITIONS = [
  ['P0001', 'Circuit de commande du régulateur de volume de carburant ouvert', 'faisceau, connecteur, régulateur ou commande', 'fuel'],
  ['P0002', 'Plage ou performance de la commande du régulateur de volume de carburant', 'pression, carburant, régulateur, pompe ou faisceau', 'fuel'],
  ['P0003', 'Commande du régulateur de volume de carburant trop basse', 'court-circuit à la masse, régulateur ou calculateur', 'fuel'],
  ['P0004', 'Commande du régulateur de volume de carburant trop haute', 'circuit ouvert, court-circuit au positif ou régulateur', 'fuel'],
  ['P0010', "Circuit de commande d'actionneur d'arbre à cames admission banque 1", 'huile, électrovanne, faisceau, distribution ou calculateur', 'timing'],
  ['P0011', "Calage d'arbre à cames admission banque 1 trop avancé ou performance", 'huile, électrovanne, déphaseur ou calage mécanique', 'timing'],
  ['P0012', "Calage d'arbre à cames admission banque 1 trop retardé", 'huile, électrovanne, déphaseur ou calage mécanique', 'timing'],
  ['P0013', "Circuit de commande d'actionneur d'arbre à cames échappement banque 1", 'faisceau, électrovanne, huile ou calculateur', 'timing'],
  ['P0014', "Calage d'arbre à cames échappement banque 1 trop avancé ou performance", 'huile, électrovanne, déphaseur ou distribution', 'timing'],
  ['P0015', "Calage d'arbre à cames échappement banque 1 trop retardé", 'huile, électrovanne, déphaseur ou distribution', 'timing'],
  ['P0016', 'Corrélation vilebrequin et arbre à cames admission banque 1', 'distribution décalée, capteur, cible, déphaseur ou faisceau', 'timing'],
  ['P0017', 'Corrélation vilebrequin et arbre à cames échappement banque 1', 'distribution décalée, capteur, cible, déphaseur ou faisceau', 'timing'],
  ['P0030', 'Circuit de chauffage de sonde lambda banque 1 capteur 1', 'chauffage, fusible, faisceau, sonde ou calculateur', 'emissions'],
  ['P0031', 'Commande de chauffage lambda banque 1 capteur 1 trop basse', 'court-circuit à la masse, sonde ou faisceau', 'emissions'],
  ['P0032', 'Commande de chauffage lambda banque 1 capteur 1 trop haute', 'circuit ouvert, court-circuit au positif ou sonde', 'emissions'],
  ['P0036', 'Circuit de chauffage de sonde lambda banque 1 capteur 2', 'chauffage, fusible, faisceau, sonde ou calculateur', 'emissions'],
  ['P0087', 'Pression de rampe ou système carburant trop basse', 'filtre, pompe, fuite, régulateur, injecteur ou capteur', 'fuel'],
  ['P0088', 'Pression de rampe ou système carburant trop haute', 'régulateur, retour obstrué, pompe, capteur ou commande', 'fuel'],
  ['P0089', 'Performance du régulateur de pression carburant', 'régulateur, pompe, capteur, injecteur ou contamination', 'fuel'],
  ['P0093', 'Fuite importante détectée dans le système carburant', 'fuite externe, injecteur, régulateur ou pression incohérente', 'fuel'],
  ['P0100', 'Circuit du débitmètre d’air', 'alimentation, masse, signal, capteur ou faisceau', 'air'],
  ['P0101', 'Plage ou performance du débitmètre d’air', 'prise d’air, filtre, capteur contaminé, EGR ou échappement', 'air'],
  ['P0102', 'Signal du débitmètre d’air trop bas', 'circuit ouvert, alimentation, capteur ou obstruction', 'air'],
  ['P0103', 'Signal du débitmètre d’air trop haut', 'court-circuit au positif, capteur ou faisceau', 'air'],
  ['P0104', 'Signal du débitmètre d’air intermittent', 'connecteur, faisceau, prise d’air ou capteur', 'air'],
  ['P0105', 'Circuit du capteur de pression admission', 'alimentation, masse, signal, capteur ou faisceau', 'air'],
  ['P0106', 'Plage ou performance de pression admission', 'prise d’air, capteur, distribution, EGR ou restriction', 'air'],
  ['P0107', 'Signal de pression admission trop bas', 'court-circuit à la masse, capteur ou référence 5 V', 'air'],
  ['P0108', 'Signal de pression admission trop haut', 'circuit ouvert, court-circuit au positif ou capteur', 'air'],
  ['P0110', "Circuit du capteur de température d'air admission", 'capteur, alimentation, masse ou faisceau', 'air'],
  ['P0112', "Température d'air admission signal trop bas", 'court-circuit à la masse, capteur ou faisceau', 'air'],
  ['P0113', "Température d'air admission signal trop haut", 'circuit ouvert, connecteur ou capteur', 'air'],
  ['P0115', 'Circuit du capteur de température de liquide moteur', 'capteur, référence, masse ou faisceau', 'cooling'],
  ['P0116', 'Plage ou performance de température liquide moteur', 'thermostat, niveau, capteur, connecteur ou circulation', 'cooling'],
  ['P0117', 'Température liquide moteur signal trop bas', 'court-circuit à la masse, capteur ou faisceau', 'cooling'],
  ['P0118', 'Température liquide moteur signal trop haut', 'circuit ouvert, connecteur ou capteur', 'cooling'],
  ['P0120', 'Circuit du capteur ou contacteur de position papillon A', 'capteur, boîtier papillon, alimentation ou faisceau', 'air'],
  ['P0121', 'Plage ou performance de position papillon A', 'encrassement, capteur, adaptation, faisceau ou papillon', 'air'],
  ['P0122', 'Position papillon A signal trop bas', 'court-circuit à la masse, capteur ou référence', 'air'],
  ['P0123', 'Position papillon A signal trop haut', 'circuit ouvert, court-circuit au positif ou capteur', 'air'],
  ['P0128', 'Température de liquide inférieure à la température régulée attendue', 'thermostat bloqué ouvert, capteur, niveau ou conditions de conduite', 'cooling'],
  ['P0130', 'Circuit sonde lambda banque 1 capteur 1', 'sonde, faisceau, fuite échappement ou richesse', 'emissions'],
  ['P0131', 'Tension lambda banque 1 capteur 1 trop basse', 'mélange pauvre, fuite, court-circuit ou sonde', 'emissions'],
  ['P0132', 'Tension lambda banque 1 capteur 1 trop haute', 'mélange riche, court-circuit ou sonde', 'emissions'],
  ['P0133', 'Réponse lente lambda banque 1 capteur 1', 'sonde vieillie, fuite, contamination ou richesse', 'emissions'],
  ['P0134', 'Absence d’activité lambda banque 1 capteur 1', 'sonde, chauffage, faisceau ou fuite', 'emissions'],
  ['P0135', 'Circuit chauffage lambda banque 1 capteur 1', 'fusible, chauffage, faisceau ou sonde', 'emissions'],
  ['P0136', 'Circuit sonde lambda banque 1 capteur 2', 'sonde, faisceau, fuite échappement ou catalyseur', 'emissions'],
  ['P0137', 'Tension lambda banque 1 capteur 2 trop basse', 'fuite, circuit, sonde ou mélange', 'emissions'],
  ['P0138', 'Tension lambda banque 1 capteur 2 trop haute', 'court-circuit, sonde ou mélange riche', 'emissions'],
  ['P0139', 'Réponse lente lambda banque 1 capteur 2', 'sonde vieillie, fuite ou catalyseur', 'emissions'],
  ['P0140', 'Absence d’activité lambda banque 1 capteur 2', 'sonde, faisceau, chauffage ou fuite', 'emissions'],
  ['P0141', 'Circuit chauffage lambda banque 1 capteur 2', 'fusible, chauffage, faisceau ou sonde', 'emissions'],
  ['P0170', 'Dysfonctionnement de correction de richesse banque 1', 'prise d’air, mesure d’air, pression, injecteurs ou sonde', 'fuel'],
  ['P0171', 'Mélange trop pauvre banque 1', 'prise d’air, débitmètre, pression carburant, injecteur ou fuite échappement', 'fuel'],
  ['P0172', 'Mélange trop riche banque 1', 'pression excessive, injecteur, mesure d’air, purge EVAP ou sonde', 'fuel'],
  ['P0174', 'Mélange trop pauvre banque 2', 'prise d’air, débitmètre, pression carburant, injecteur ou fuite échappement', 'fuel'],
  ['P0175', 'Mélange trop riche banque 2', 'pression excessive, injecteur, mesure d’air, purge EVAP ou sonde', 'fuel'],
  ['P0190', 'Circuit du capteur de pression de rampe carburant', 'capteur, référence, masse, signal ou faisceau', 'fuel'],
  ['P0191', 'Plage ou performance du capteur de pression de rampe', 'pression réelle, capteur, régulateur, pompe ou faisceau', 'fuel'],
  ['P0192', 'Signal de pression de rampe trop bas', 'court-circuit à la masse, pression basse ou capteur', 'fuel'],
  ['P0193', 'Signal de pression de rampe trop haut', 'circuit ouvert, pression haute ou capteur', 'fuel'],
  ['P0200', 'Circuit de commande des injecteurs', 'alimentation, faisceau, injecteur ou calculateur', 'fuel'],
  ['P0201', 'Circuit injecteur cylindre 1', 'injecteur, connecteur, faisceau ou calculateur', 'fuel'],
  ['P0202', 'Circuit injecteur cylindre 2', 'injecteur, connecteur, faisceau ou calculateur', 'fuel'],
  ['P0203', 'Circuit injecteur cylindre 3', 'injecteur, connecteur, faisceau ou calculateur', 'fuel'],
  ['P0204', 'Circuit injecteur cylindre 4', 'injecteur, connecteur, faisceau ou calculateur', 'fuel'],
  ['P0205', 'Circuit injecteur cylindre 5', 'injecteur, connecteur, faisceau ou calculateur', 'fuel'],
  ['P0206', 'Circuit injecteur cylindre 6', 'injecteur, connecteur, faisceau ou calculateur', 'fuel'],
  ['P0217', 'Surchauffe moteur détectée', 'niveau, fuite, thermostat, pompe, ventilateur ou capteur', 'cooling'],
  ['P0220', 'Circuit de position papillon ou pédale B', 'capteur, alimentation, faisceau ou boîtier papillon', 'air'],
  ['P0234', 'Condition de suralimentation excessive', 'commande turbo, géométrie, wastegate, capteur ou durite', 'air'],
  ['P0299', 'Pression de suralimentation insuffisante', 'fuite, commande, turbo, capteur ou échappement', 'air'],
  ['P0300', 'Ratés de combustion aléatoires ou multiples', 'allumage, injection, prise d’air, carburant ou mécanique', 'ignition'],
  ['P0301', 'Ratés de combustion cylindre 1', 'allumage, injection, prise d’air ou mécanique', 'ignition'],
  ['P0302', 'Ratés de combustion cylindre 2', 'allumage, injection, prise d’air ou mécanique', 'ignition'],
  ['P0303', 'Ratés de combustion cylindre 3', 'allumage, injection, prise d’air ou mécanique', 'ignition'],
  ['P0304', 'Ratés de combustion cylindre 4', 'allumage, injection, prise d’air ou mécanique', 'ignition'],
  ['P0305', 'Ratés de combustion cylindre 5', 'allumage, injection, prise d’air ou mécanique', 'ignition'],
  ['P0306', 'Ratés de combustion cylindre 6', 'allumage, injection, prise d’air ou mécanique', 'ignition'],
  ['P0307', 'Ratés de combustion cylindre 7', 'allumage, injection, prise d’air ou mécanique', 'ignition'],
  ['P0308', 'Ratés de combustion cylindre 8', 'allumage, injection, prise d’air ou mécanique', 'ignition'],
  ['P0325', 'Circuit du capteur de cliquetis 1', 'capteur, serrage, faisceau, bruit mécanique ou calculateur', 'ignition'],
  ['P0335', 'Circuit du capteur de position vilebrequin A', 'capteur, cible, alimentation, faisceau ou entrefer', 'timing'],
  ['P0336', 'Plage ou performance du capteur vilebrequin A', 'signal perturbé, cible, entrefer, distribution ou capteur', 'timing'],
  ['P0340', "Circuit du capteur de position d'arbre à cames A banque 1", 'capteur, cible, alimentation, faisceau ou distribution', 'timing'],
  ['P0341', "Plage ou performance du capteur d'arbre à cames A banque 1", 'signal, cible, déphaseur, distribution ou capteur', 'timing'],
  ['P0351', 'Circuit primaire ou secondaire de bobine A', 'bobine, bougie, alimentation, faisceau ou calculateur', 'ignition'],
  ['P0352', 'Circuit primaire ou secondaire de bobine B', 'bobine, bougie, alimentation, faisceau ou calculateur', 'ignition'],
  ['P0353', 'Circuit primaire ou secondaire de bobine C', 'bobine, bougie, alimentation, faisceau ou calculateur', 'ignition'],
  ['P0354', 'Circuit primaire ou secondaire de bobine D', 'bobine, bougie, alimentation, faisceau ou calculateur', 'ignition'],
  ['P0400', 'Dysfonctionnement du débit EGR', 'vanne, conduits, commande, capteur ou faisceau', 'emissions'],
  ['P0401', 'Débit EGR insuffisant', 'conduits obstrués, vanne, commande ou mesure d’air', 'emissions'],
  ['P0402', 'Débit EGR excessif', 'vanne bloquée, commande, capteur ou conduits', 'emissions'],
  ['P0403', 'Circuit de commande EGR', 'alimentation, faisceau, actionneur ou calculateur', 'emissions'],
  ['P0420', 'Efficacité catalyseur sous le seuil banque 1', 'ratés, richesse, fuite échappement, sonde ou catalyseur', 'emissions'],
  ['P0430', 'Efficacité catalyseur sous le seuil banque 2', 'ratés, richesse, fuite échappement, sonde ou catalyseur', 'emissions'],
  ['P0440', 'Dysfonctionnement du système de vapeurs de carburant EVAP', 'bouchon, fuite, purge, mise à l’air ou faisceau', 'emissions'],
  ['P0441', 'Débit de purge EVAP incorrect', 'électrovanne, obstruction, fuite ou commande', 'emissions'],
  ['P0442', 'Petite fuite détectée dans le système EVAP', 'bouchon, durite, joint, canister ou vanne', 'emissions'],
  ['P0443', 'Circuit de commande de purge EVAP', 'électrovanne, alimentation, faisceau ou calculateur', 'emissions'],
  ['P0446', 'Circuit de commande de mise à l’air EVAP', 'vanne, filtre, faisceau, obstruction ou calculateur', 'emissions'],
  ['P0455', 'Fuite importante détectée dans le système EVAP', 'bouchon absent, durite débranchée, vanne ou canister', 'emissions'],
  ['P0456', 'Très petite fuite détectée dans le système EVAP', 'joint, bouchon, microfuite, vanne ou canister', 'emissions'],
  ['P0480', 'Circuit de commande du ventilateur de refroidissement 1', 'fusible, relais, moteur, module, faisceau ou calculateur', 'cooling'],
  ['P0481', 'Circuit de commande du ventilateur de refroidissement 2', 'fusible, relais, moteur, module, faisceau ou calculateur', 'cooling'],
  ['P0500', 'Dysfonctionnement du capteur de vitesse véhicule', 'capteur de roue/boîte, faisceau, réseau ou calculateur', 'electrical'],
  ['P0505', 'Dysfonctionnement du système de régulation de ralenti', 'prise d’air, papillon, actionneur, adaptation ou faisceau', 'air'],
  ['P0506', 'Régime de ralenti inférieur à la consigne', 'encrassement, charge, prise d’air, adaptation ou moteur', 'air'],
  ['P0507', 'Régime de ralenti supérieur à la consigne', 'prise d’air, papillon, purge EVAP ou adaptation', 'air'],
  ['P0560', 'Dysfonctionnement de tension système', 'batterie, alternateur, câblage, masse ou gestion de charge', 'electrical'],
  ['P0562', 'Tension système trop basse', 'batterie, charge, résistance de câble ou consommation', 'electrical'],
  ['P0563', 'Tension système trop haute', 'régulation alternateur, masse, capteur batterie ou commande', 'electrical'],
  ['P0600', 'Dysfonctionnement de liaison de communication série', 'alimentation, masse, bus, connecteur ou module', 'network'],
  ['P0601', 'Erreur de somme de contrôle mémoire interne du calculateur', 'tension, programmation, alimentation ou calculateur', 'electrical'],
  ['P0602', 'Erreur de programmation du module de commande', 'logiciel, configuration, tension ou module', 'electrical'],
  ['P0603', 'Erreur de mémoire vive permanente du module', 'batterie débranchée, alimentation, mémoire ou module', 'electrical'],
  ['P0606', 'Performance du processeur du module de commande', 'alimentation, masse, logiciel, perturbation ou module', 'electrical'],
  ['P0700', 'Demande d’allumage du voyant par la transmission', 'un ou plusieurs défauts détaillés sont mémorisés dans le calculateur de boîte', 'transmission'],
  ['P0715', "Circuit du capteur de vitesse d'entrée ou turbine", 'capteur, faisceau, connecteur, roue phonique ou boîte', 'transmission'],
  ['P0717', "Absence de signal du capteur de vitesse d'entrée ou turbine", 'circuit ouvert, capteur, roue phonique ou module', 'transmission'],
  ['P0720', 'Circuit du capteur de vitesse de sortie', 'capteur, faisceau, connecteur, roue phonique ou boîte', 'transmission'],
  ['P0722', 'Absence de signal du capteur de vitesse de sortie', 'circuit ouvert, capteur, roue phonique ou module', 'transmission'],
  ['P0730', 'Rapport de transmission incorrect', 'niveau/pression, glissement, électrovanne, embrayage interne ou capteur', 'transmission'],
  ['P0731', 'Rapport incorrect en première', 'pression, électrovanne, embrayage interne, capteur ou mécanique', 'transmission'],
  ['P0732', 'Rapport incorrect en deuxième', 'pression, électrovanne, embrayage interne, capteur ou mécanique', 'transmission'],
  ['P0733', 'Rapport incorrect en troisième', 'pression, électrovanne, embrayage interne, capteur ou mécanique', 'transmission'],
  ['P0734', 'Rapport incorrect en quatrième', 'pression, électrovanne, embrayage interne, capteur ou mécanique', 'transmission'],
  ['P0740', 'Circuit de commande de l’embrayage de convertisseur', 'électrovanne, faisceau, fluide, hydraulique ou convertisseur', 'transmission'],
  ['P0741', 'Performance ou blocage ouvert de l’embrayage de convertisseur', 'fluide, pression, électrovanne, convertisseur ou usure interne', 'transmission'],
  ['P0750', 'Dysfonctionnement de l’électrovanne de changement A', 'électrovanne, faisceau, fluide, hydraulique ou module', 'transmission'],
  ['P0755', 'Dysfonctionnement de l’électrovanne de changement B', 'électrovanne, faisceau, fluide, hydraulique ou module', 'transmission'],
  ['P0760', 'Dysfonctionnement de l’électrovanne de changement C', 'électrovanne, faisceau, fluide, hydraulique ou module', 'transmission'],
  ['P2002', 'Efficacité du filtre à particules sous le seuil banque 1', 'filtre chargé/endommagé, fuite, capteur de pression ou régénération', 'emissions'],
  ['P2015', 'Plage ou performance de position du volet de collecteur banque 1', 'tringlerie, dépôts, actionneur, capteur ou faisceau', 'air'],
  ['P20EE', 'Efficacité du catalyseur SCR NOx sous le seuil banque 1', 'qualité/dosage AdBlue, fuite, capteur NOx, température ou catalyseur', 'emissions'],
  ['P2201', 'Plage ou performance du circuit capteur NOx banque 1', 'capteur, alimentation, faisceau, fuite ou conditions moteur', 'emissions'],
  ['P2452', 'Circuit du capteur de pression différentielle du filtre à particules', 'capteur, tuyaux, alimentation, faisceau ou filtre', 'emissions'],
  ['P2463', 'Accumulation excessive de suies dans le filtre à particules', 'trajets, défaut moteur, capteur, régénération ou filtre chargé', 'emissions'],
  ['U0001', 'Dysfonctionnement du bus CAN haute vitesse', 'alimentation, masse, câblage, terminaison, court-circuit ou module', 'network'],
  ['U0100', 'Communication perdue avec le calculateur moteur ou groupe motopropulseur', 'alimentation, masse, bus, connecteur ou calculateur', 'network'],
  ['U0101', 'Communication perdue avec le calculateur de transmission', 'alimentation, masse, bus, connecteur ou calculateur', 'network'],
  ['U0121', 'Communication perdue avec le calculateur ABS', 'alimentation, masse, bus, connecteur ou calculateur ABS', 'network'],
  ['U0140', 'Communication perdue avec le module de carrosserie', 'alimentation, masse, bus, connecteur ou module', 'network'],
  ['U0151', 'Communication perdue avec le module de retenue/airbag', 'alimentation, masse, bus, connecteur ou module SRS', 'network'],
];

for (const [code, condition, possibleCauses, family] of EXTRA_OBD_DEFINITIONS) {
  OBD_SCENARIOS[code] = createObdScenario(code, condition, possibleCauses, family);
}
